---
title: ''
pagetitle: Adam N. Smith
theme: minima
---

<h1> Adam N. Smith </h1> 

<h3>
[about](index.html) / 
<a href=files/smith-cv.pdf target="_blank">cv</a> /
research /
[teaching](teaching.html) /
[notes](notes.html) /
<a href="https://github.com/adam-n-smith" target="_blank">github</a>
</h3> 

<h2> Publications </h2>

1. [Inference for Product Competition and Separable Demand](files/research/separabledemand.pdf)\
***Marketing Science***, with Peter Rossi and Greg Allenby (2019)\
<a 
href="files/research/separabledemand_appendix.pdf" 
style="color:rgb(51,51,51);">[online appendix]</a>

2. [Demand Models with Random Partitions](files/research/dmrp.pdf)\
***Journal of the American Statistical Association***, with Greg Allenby (2020)\
<a 
href="files/research/dmrp_appendix.pdf" 
style="color:rgb(51,51,51);">[online appendix]</a>
<a 
href="https://github.com/adam-n-smith/demand-models-random-partitions" 
style="color:rgb(51,51,51);">[code]</a>

3. [Discussion of "Centered Partition Processes: Informative Priors for Clustering"](files/research/cp_discussion.pdf)\
***Bayesian Analysis*** (2021)\


<h2> Current Research </h2>

1. [Optimal Price Targeting](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3822459)\
R&R at ***Marketing Science***, with Stephan Seiler and Ishant Aggarwal (Apr 2021)\
<a 
href="https://cepr.org/active/publications/discussion_papers/dp.php?dpno=16096" 
style="color:rgb(51,51,51);">[CEPR DP]
</a>
<a 
href="https://www.cesifo.org/en/publikationen/2021/working-paper/optimal-price-targeting" 
style="color:rgb(51,51,51);">[CESifo WP]
</a>

2. [Shrinkage Priors for High-Dimensional Demand Estimation](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3833417)\
R&R at ***Quantitative Marketing and Economics***, with Jim Griffin (Apr 2021)

3. [Boundaries of Differentiated Product Markets and Retailer Pricing](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3916922)\
with Giovanni Compiani (Sep 2021)

4. [Integrated Factor Models of Variety Seeking Dynamics](files/research/preference_dynamics.pdf) \
with Yinxing Li, Shohei Hasegawa, Nobuhiko Terui, and Greg Allenby (Aug 2020)

5. [Capturing Flexible Price Elasticities in Direct Utility Models](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3539001)\
with Chul Kim, Jaehwan Kim, and Greg Allenby (Mar 2020)

6. Learned Complementarity\
with Dan Ershov

7. Constrained Heterogeneity\
with Tetyana Kosyakova, Thomas Otter, and Max Pachali

<br>